name: CI
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          sudo apt-get update && sudo apt-get install -y build-essential cmake libssl-dev libspdlog-dev nlohmann-json3-dev libcurl4-openssl-dev libncurses5-dev libncursesw5-dev cppcheck clang-tidy
        fi
    - name: Setup vcpkg (Windows)
      id: vcpkg
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        git clone --depth 1 https://github.com/microsoft/vcpkg.git vcpkg
        .\vcpkg\bootstrap-vcpkg.bat
        Add-Content -Path $Env:GITHUB_OUTPUT -Value "vcpkgRoot=$PWD\\vcpkg"
    - name: Cache vcpkg installed packages
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v3
      with:
        path: vcpkg/installed
        key: ${{ runner.os }}-vcpkg-installed
        restore-keys: |
          ${{ runner.os }}-vcpkg-installed-

    - name: Install vcpkg libs (Windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        .\vcpkg\vcpkg.exe install openssl:x64-windows spdlog:x64-windows nlohmann-json:x64-windows curl:x64-windows
    - name: Build (Linux)
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --config Release

    - name: Build (Windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        New-Item -ItemType Directory -Path build
        Set-Location build
        cmake -DCMAKE_TOOLCHAIN_FILE="${{ steps.vcpkg.outputs.vcpkgRoot }}\scripts\buildsystems\vcpkg.cmake" -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --config Release
    - name: Static analysis
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd build
        cppcheck ../src ../include
        clang-tidy ../src/*.cpp -- -I../include
    - name: Create Release and upload binary
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: |
          build/pwdmgr
          build/Release/pwdmgr.exe 